/**
 * NHIA (National Health Insurance Authority) Accredited HMO Master Directory.
 * Deduplicated master list with 93 unique accredited organizations.
 * Retains authoritative NHIA HMO IDs (including Health Assur Limited IDs 87 & 128).
 */

export const NHIA_HMO_DIRECTORY = [
  { name: "A&M Healthcare Trust Limited" },
  { name: "AIICO Multishield Nigeria Limited" },
  { name: "Alleanza Health Management Limited" },
  { name: "Ally Healthcare Limited" },
  { name: "Aman Health Maintenance Organizations" },
  { name: "Anchor HMO International Company Limited" },
  { name: "Ashmed Integrated Health Services Ltd." },
  { name: "Aspire HMO Limited" },
  { name: "Avon Healthcare Limited" },
  { name: "AXA Mansard Health Limited" },
  { name: "Bastion Health Limited" },
  { name: "Bonitas Health Maintenance Limited" },
  { name: "Century Medicaid Services Limited" },
  { name: "Clearline International Limited" },
  { name: "Crown Jewel HMO Ltd." },
  { name: "Defence Health Maintenance Limited" },
  { name: "Delog Medical Services Ltd. (HMO)" },
  { name: "Doheec International Healthcare Limited HMO" },
  { name: "DOT HMO Ltd." },
  { name: "Fountain Healthcare Limited" },
  { name: "GNI Healthcare Ltd" },
  { name: "Gorah Healthcare Ltd." },
  { name: "Greenbay Healthcare Services Limited" },
  { name: "Greenfield Health Management Ltd" },
  { name: "Grooming Health Management Limited" },
  { name: "Hallmark Health Services Limited" },
  { name: "Health Assur Limited", nhiaId: [87, 128] },
  { name: "Healthcare International Limited" },
  { name: "Healthnomics HMO PLC" },
  { name: "Health Partners Limited" },
  { name: "Healthspring HMO" },
  { name: "Hopewell Healthcare Management Ltd" },
  { name: "Hygeia HMO Limited" },
  { name: "HYSSOP Health International Limited (HMO)" },
  { name: "Infinite X2 Health Maintenance Services" },
  { name: "Integrated Healthcare" },
  { name: "International Health Mgt. Services" },
  { name: "Ives Medicare" },
  { name: "Kennedia HMO Limited" },
  { name: "Leadway Health Limited" },
  { name: "Life Action Plus Ltd." },
  { name: "Lifesaver Healthcare Limited" },
  { name: "Life Worth Medicare Ltd" },
  { name: "Maayoit Health Care Limited" },
  { name: "Marina Medical Services HMO Limited" },
  { name: "Markfema Nigeria Ltd." },
  { name: "Masslife Healthcare Limited" },
  { name: "MB & O Healthcare Services Limited" },
  { name: "Medexia Limited" },
  { name: "Medicare Alliance Limited" },
  { name: "Mediplan Healthcare Limited" },
  { name: "Metrohealth HMO Limited" },
  { name: "Mitera Health Limited" },
  { name: "NEM Health Limited" },
  { name: "NNPC-HMO Limited" },
  { name: "Nonsuch Medicare Limited" },
  { name: "Noor Health Ltd." },
  { name: "Novo Health Africa Limited" },
  { name: "Oceanic Health Management Limited" },
  { name: "Peramare Health Management Company Limited" },
  { name: "Phillips Health Management Services Limited" },
  { name: "Police Health Maintenance Limited" },
  { name: "Precious Healthcare Limited" },
  { name: "Prepaid Medicare Services Ltd." },
  { name: "Princeton Health" },
  { name: "ProHealth HMO Ltd" },
  { name: "Quest Medicare Limited" },
  { name: "Redcare Health Services Limited" },
  { name: "Regenix Health Care Service Limited" },
  { name: "Reliance HMO Limited" },
  { name: "Roding Healthcare Ltd." },
  { name: "Ronsberger Nigeria Ltd." },
  { name: "Rothauge Healthcare Limited" },
  { name: "Royal Health Maintenance Services Ltd." },
  { name: "Salus Trust GTE" },
  { name: "Seraph HMO Limited" },
  { name: "Skyda Health Limited" },
  { name: "Smathealth Medicare Limited" },
  { name: "Songhai Health Trust" },
  { name: "Springtide Healthcare Services Ltd." },
  { name: "Sterling Health Managed Care Services Limited" },
  { name: "Sunu Health Nigeria Limited" },
  { name: "Synergy Wellcare Medicaid Limited" },
  { name: "Total Health Trust Limited" },
  { name: "Ultimate Health Management Services Ltd" },
  { name: "United Comprehensive Health Managers Ltd." },
  { name: "United Healthcare International Limited" },
  { name: "Venus Medicare Ltd" },
  { name: "Veritas Healthcare Limited" },
  { name: "Well Health Network Limited" },
  { name: "Wellness Health Management Services Limited" },
  { name: "Zenor Healthcare Ltd." },
  { name: "Zuma Health Trust" },
];
